name: grock_dart
description: Dart language version of the Grock package.
version: 0.1.1
repository: https://github.com/ahmet-ozberk/grock_dart

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
